spring:
  web:
    resources:
      add-mappings: false
  application:
    name: teatime-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teatime?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: teatime
    password: qwer1234
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      idleTimeout: 300
      maxLifeTime: 300
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    open-in-view: false
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html


jwt:
  secret-key: 7DulQvT+WYY5q0FFjH6sBnc9hVEeQeeIOc4Zy7i9hw2UCMHeoTCM7RH2Y26mfesalooCXdFA36IRd4W/6qDh6Q==
  access-token-expire-period: 7200
  refresh-token-expire-period: 1209600
server:
  port: 8081
cloud:
  aws:
    s3:
      bucket: teatime-api
    credentials:
      access-key: qwer
      secret-key: qwer
    region:
      static: ap-northeast-2
    stack:
      auto: false
